name: squid-flask-proxy

services:
  admin-ui:
    extends:
      file: docker-compose.common.yml
      service: admin-ui
    build:
      context: .
      dockerfile: docker/Dockerfile.admin
      pull: true

  proxy:
    extends:
      file: docker-compose.common.yml
      service: proxy
    build:
      context: .
      dockerfile: docker/Dockerfile.proxy
      pull: true

volumes:
  squid_cache:
  squid_ssl_db:
  proxy_data:

networks:
  control:
