from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from html import escape
from pathlib import Path
import re
from typing import Iterable


@dataclass(frozen=True)
class ErrorPageInfo:
    name: str
    title: str
    family: str
    audience: str
    description: str
    admin_guidance: str
    high_priority: bool = False
    custom: bool = False


SQUID_ERROR_TEMPLATE_NAMES: tuple[str, ...] = (
    "ERR_ACCESS_DENIED",
    "ERR_ACL_TIME_QUOTA_EXCEEDED",
    "ERR_AGENT_CONFIGURE",
    "ERR_AGENT_WPAD",
    "ERR_CACHE_ACCESS_DENIED",
    "ERR_CACHE_MGR_ACCESS_DENIED",
    "ERR_CANNOT_FORWARD",
    "ERR_CONFLICT_HOST",
    "ERR_CONNECT_FAIL",
    "ERR_DIR_LISTING",
    "ERR_DNS_FAIL",
    "ERR_ESI",
    "ERR_FORWARDING_DENIED",
    "ERR_FTP_DISABLED",
    "ERR_FTP_FAILURE",
    "ERR_FTP_FORBIDDEN",
    "ERR_FTP_NOT_FOUND",
    "ERR_FTP_PUT_CREATED",
    "ERR_FTP_PUT_ERROR",
    "ERR_FTP_PUT_MODIFIED",
    "ERR_FTP_UNAVAILABLE",
    "ERR_GATEWAY_FAILURE",
    "ERR_ICAP_FAILURE",
    "ERR_INVALID_REQ",
    "ERR_INVALID_RESP",
    "ERR_INVALID_URL",
    "ERR_LIFETIME_EXP",
    "ERR_NO_RELAY",
    "ERR_ONLY_IF_CACHED_MISS",
    "ERR_PRECONDITION_FAILED",
    "ERR_PROTOCOL_UNKNOWN",
    "ERR_READ_ERROR",
    "ERR_READ_TIMEOUT",
    "ERR_SECURE_CONNECT_FAIL",
    "ERR_SHUTTING_DOWN",
    "ERR_SOCKET_FAILURE",
    "ERR_TOO_BIG",
    "ERR_UNSUP_HTTPVERSION",
    "ERR_UNSUP_REQ",
    "ERR_URN_RESOLVE",
    "ERR_WRITE_ERROR",
    "ERR_ZERO_SIZE_OBJECT",
)

CUSTOM_ERROR_TEMPLATE_NAMES: tuple[str, ...] = ("ERR_WEBFILTER_BLOCKED",)

SAFE_USER_TOKENS: tuple[tuple[str, str], ...] = (
    ("%c", "Squid error code/name"),
    ("%T", "UTC timestamp"),
    ("%t", "local timestamp"),
    ("%h", "proxy hostname"),
    ("%s", "proxy software/version"),
    ("%U", "requested URL without password"),
    ("%M", "request method"),
    ("%P", "request protocol"),
    ("%H", "destination host"),
    ("%p", "destination port"),
    ("%i", "client IP address"),
    ("%w", "administrator contact email"),
)

ADMIN_DIAGNOSTIC_TOKENS: tuple[tuple[str, str], ...] = (
    ("%D", "Squid error details; useful for TLS/cert failures"),
    ("%Z", "preformatted process/helper error message"),
    ("%m", "authentication helper message"),
    ("%o", "external ACL helper message"),
    ("%z", "DNS server error message"),
    ("%E", "system strerror output"),
    ("%e", "system errno"),
    ("%R", "full HTTP request; may expose headers/request details"),
    ("%u", "URL including password; avoid on end-user pages"),
    ("%W", "URL-encoded error data for mail links"),
)

_TOKEN_RE = re.compile(r"%(?:%|[a-zA-Z])")
_SAMPLE_VALUES = {
    "%a": "j.smith",
    "%A": "192.0.2.10",
    "%B": "https://example.invalid/report.pdf",
    "%c": "ERR_ACCESS_DENIED",
    "%d": "1.284",
    "%D": "TLS certificate validation failed: issuer is not trusted",
    "%e": "111",
    "%E": "Connection refused",
    "%f": "RETR /pub/example.txt",
    "%F": "550 File unavailable",
    "%g": "FTP server rejected the requested path",
    "%h": "proxy-edge-1",
    "%H": "example.invalid",
    "%i": "192.0.2.44",
    "%I": "203.0.113.25",
    "%l": "",
    "%L": "Contact your proxy administrator if this block is unexpected.",
    "%M": "GET",
    "%m": "Authentication helper denied the credentials",
    "%o": "webfilter category: malware",
    "%p": "443",
    "%P": "HTTPS",
    "%R": "GET https://example.invalid/report.pdf HTTP/1.1",
    "%S": "Generated by Docker Proxy",
    "%s": "Squid proxy",
    "%t": "Sun, 10 May 2026 08:15:30 MST",
    "%T": "Sun, 10 May 2026 15:15:30 GMT",
    "%U": "https://example.invalid/report.pdf",
    "%u": "https://user:password@example.invalid/report.pdf",
    "%w": "proxy-admin@example.invalid",
    "%W": "ERR_ACCESS_DENIED%20https%3A%2F%2Fexample.invalid%2Freport.pdf",
    "%x": "policy/security",
    "%z": "NXDOMAIN from resolver 192.0.2.53",
    "%Z": "helper exited before returning a decision",
    "%%": "%",
}

_INFO: dict[str, ErrorPageInfo] = {
    "ERR_ACCESS_DENIED": ErrorPageInfo("ERR_ACCESS_DENIED", "Access blocked by policy", "Access control", "User + admin", "The proxy policy denied this request before it reached the destination.", "Check the requested URL, client identity, source network, and matching access/web-filter rules.", True),
    "ERR_ACL_TIME_QUOTA_EXCEEDED": ErrorPageInfo("ERR_ACL_TIME_QUOTA_EXCEEDED", "Time or quota limit reached", "Access control", "User + admin", "A time or quota based access-control rule matched this request.", "Review quota/time ACLs for this user, client, or destination.", True),
    "ERR_AGENT_CONFIGURE": ErrorPageInfo("ERR_AGENT_CONFIGURE", "Proxy auto-configuration required", "Client configuration", "User + admin", "The client needs proxy auto-configuration before this request can continue.", "Verify PAC/WPAD deployment and client proxy discovery settings."),
    "ERR_AGENT_WPAD": ErrorPageInfo("ERR_AGENT_WPAD", "WPAD configuration required", "Client configuration", "User + admin", "The client requested automatic proxy discovery support.", "Verify WPAD DNS/DHCP and PAC publishing for this network."),
    "ERR_CACHE_ACCESS_DENIED": ErrorPageInfo("ERR_CACHE_ACCESS_DENIED", "Cache access denied", "Cache manager", "Admin", "The request attempted to use a cache function that policy does not allow.", "Review cache manager, PURGE, and internal-object ACLs.", True),
    "ERR_CACHE_MGR_ACCESS_DENIED": ErrorPageInfo("ERR_CACHE_MGR_ACCESS_DENIED", "Cache manager access denied", "Cache manager", "Admin", "Access to Squid cache-manager data was blocked.", "Only trusted admin sources should be allowed to manager endpoints.", True),
    "ERR_CANNOT_FORWARD": ErrorPageInfo("ERR_CANNOT_FORWARD", "Unable to forward request", "Forwarding", "User + admin", "The proxy could not select a valid forwarding path for this request.", "Check parent proxy, routing, DNS, and peer selection policy.", True),
    "ERR_CONFLICT_HOST": ErrorPageInfo("ERR_CONFLICT_HOST", "Conflicting host information", "Request validation", "User + admin", "The URL host and HTTP Host header do not agree.", "Investigate malformed clients, interception mode, or host header tampering.", True),
    "ERR_CONNECT_FAIL": ErrorPageInfo("ERR_CONNECT_FAIL", "Connection to destination failed", "Connectivity", "User + admin", "The proxy could not establish a TCP connection to the origin server.", "Check destination reachability, firewall policy, routing, and port availability.", True),
    "ERR_DIR_LISTING": ErrorPageInfo("ERR_DIR_LISTING", "Directory listing", "FTP", "User", "The requested FTP or directory resource was returned as a listing.", "Confirm whether directory browsing is expected for this destination."),
    "ERR_DNS_FAIL": ErrorPageInfo("ERR_DNS_FAIL", "DNS lookup failed", "DNS", "User + admin", "The proxy could not resolve the destination name.", "Check DNS servers, split-horizon records, and the requested hostname.", True),
    "ERR_ESI": ErrorPageInfo("ERR_ESI", "Edge-side include processing failed", "Content processing", "Admin", "The proxy encountered an ESI processing problem.", "Review origin content and ESI handling policy."),
    "ERR_FORWARDING_DENIED": ErrorPageInfo("ERR_FORWARDING_DENIED", "Forwarding denied", "Forwarding", "User + admin", "Forwarding policy prevented this request from leaving the proxy.", "Review forwarding ACLs, peer rules, and destination restrictions.", True),
    "ERR_FTP_DISABLED": ErrorPageInfo("ERR_FTP_DISABLED", "FTP access disabled", "FTP", "User + admin", "FTP handling is disabled on this proxy.", "Enable FTP support only if it is operationally required."),
    "ERR_FTP_FAILURE": ErrorPageInfo("ERR_FTP_FAILURE", "FTP transaction failed", "FTP", "User + admin", "The proxy encountered an FTP protocol or transfer failure.", "Review FTP server response, credentials, and protocol compatibility."),
    "ERR_FTP_FORBIDDEN": ErrorPageInfo("ERR_FTP_FORBIDDEN", "FTP access forbidden", "FTP", "User + admin", "The FTP server or proxy policy denied access to this resource.", "Check FTP permissions and proxy ACLs."),
    "ERR_FTP_NOT_FOUND": ErrorPageInfo("ERR_FTP_NOT_FOUND", "FTP resource not found", "FTP", "User", "The requested FTP path was not found.", "Verify the server, path, and file name."),
    "ERR_FTP_PUT_CREATED": ErrorPageInfo("ERR_FTP_PUT_CREATED", "FTP upload created", "FTP", "Admin", "The FTP upload created a new resource.", "Confirm upload policy and destination path."),
    "ERR_FTP_PUT_ERROR": ErrorPageInfo("ERR_FTP_PUT_ERROR", "FTP upload failed", "FTP", "User + admin", "The FTP upload could not be completed.", "Review FTP permissions, quota, path, and server response."),
    "ERR_FTP_PUT_MODIFIED": ErrorPageInfo("ERR_FTP_PUT_MODIFIED", "FTP upload modified", "FTP", "Admin", "The FTP upload modified an existing resource.", "Confirm this write operation was expected."),
    "ERR_FTP_UNAVAILABLE": ErrorPageInfo("ERR_FTP_UNAVAILABLE", "FTP service unavailable", "FTP", "User + admin", "The FTP service could not process the request.", "Check FTP server availability and proxy FTP support."),
    "ERR_GATEWAY_FAILURE": ErrorPageInfo("ERR_GATEWAY_FAILURE", "Gateway failure", "Upstream", "User + admin", "An upstream gateway or peer failed while processing this request.", "Check parent proxies, ICAP services, routing, and upstream health.", True),
    "ERR_ICAP_FAILURE": ErrorPageInfo("ERR_ICAP_FAILURE", "Content adaptation failed", "ICAP", "User + admin", "An ICAP service failed or returned an unusable response.", "Check adblock/antivirus ICAP service health and timeout settings.", True),
    "ERR_INVALID_REQ": ErrorPageInfo("ERR_INVALID_REQ", "Invalid request", "Request validation", "User + admin", "The client sent a request the proxy could not parse or accept.", "Inspect client behavior, request headers, method, and protocol version.", True),
    "ERR_INVALID_RESP": ErrorPageInfo("ERR_INVALID_RESP", "Invalid server response", "Origin response", "User + admin", "The origin server returned a response the proxy could not parse or accept.", "Inspect origin behavior, TLS interception state, and response headers.", True),
    "ERR_INVALID_URL": ErrorPageInfo("ERR_INVALID_URL", "Invalid URL", "Request validation", "User + admin", "The requested URL is malformed or unsupported.", "Verify the client request and URL format.", True),
    "ERR_LIFETIME_EXP": ErrorPageInfo("ERR_LIFETIME_EXP", "Request lifetime expired", "Timeout", "User + admin", "The request exceeded the proxy lifetime limit before completion.", "Check slow upstreams, large transfers, and timeout policy.", True),
    "ERR_NO_RELAY": ErrorPageInfo("ERR_NO_RELAY", "Relay unavailable", "Forwarding", "Admin", "The proxy could not find a relay service for this request.", "Review relay/peer configuration."),
    "ERR_ONLY_IF_CACHED_MISS": ErrorPageInfo("ERR_ONLY_IF_CACHED_MISS", "Cached copy unavailable", "Cache", "User", "The client requested only cached content, but no valid cached object exists.", "Retry without only-if-cached or pre-warm the cache if required.", True),
    "ERR_PRECONDITION_FAILED": ErrorPageInfo("ERR_PRECONDITION_FAILED", "Request precondition failed", "Origin response", "User", "A request precondition could not be satisfied.", "Review conditional headers and origin object state."),
    "ERR_PROTOCOL_UNKNOWN": ErrorPageInfo("ERR_PROTOCOL_UNKNOWN", "Unknown protocol", "Protocol", "User + admin", "The request used a protocol the proxy does not support.", "Verify URL scheme, CONNECT target, and allowed protocol policy.", True),
    "ERR_READ_ERROR": ErrorPageInfo("ERR_READ_ERROR", "Read error", "Connectivity", "User + admin", "The proxy encountered an error reading from the server or client connection.", "Check network stability, origin health, and connection resets.", True),
    "ERR_READ_TIMEOUT": ErrorPageInfo("ERR_READ_TIMEOUT", "Read timeout", "Timeout", "User + admin", "The proxy timed out waiting for data.", "Check origin performance, network latency, and timeout settings.", True),
    "ERR_SECURE_CONNECT_FAIL": ErrorPageInfo("ERR_SECURE_CONNECT_FAIL", "Secure connection failed", "TLS", "User + admin", "The proxy could not establish or validate the TLS connection.", "Review certificate errors, SSL bump policy, SNI, and TLS compatibility settings.", True),
    "ERR_SHUTTING_DOWN": ErrorPageInfo("ERR_SHUTTING_DOWN", "Proxy is shutting down", "Service state", "User + admin", "The proxy is stopping and cannot process this request.", "Wait for service recovery or check deployment/restart activity.", True),
    "ERR_SOCKET_FAILURE": ErrorPageInfo("ERR_SOCKET_FAILURE", "Socket failure", "Connectivity", "User + admin", "The proxy encountered a socket-level network failure.", "Check network path, NAT/firewall state, and system socket limits.", True),
    "ERR_TOO_BIG": ErrorPageInfo("ERR_TOO_BIG", "Request or response too large", "Policy limit", "User + admin", "The transaction exceeded a configured proxy size limit.", "Review body/header/object size limits and the requested content.", True),
    "ERR_UNSUP_HTTPVERSION": ErrorPageInfo("ERR_UNSUP_HTTPVERSION", "Unsupported HTTP version", "Protocol", "User + admin", "The client or server used an HTTP version unsupported by this proxy path.", "Review client protocol settings and proxy listener mode.", True),
    "ERR_UNSUP_REQ": ErrorPageInfo("ERR_UNSUP_REQ", "Unsupported request", "Protocol", "User + admin", "The request method or feature is unsupported by this proxy path.", "Review client method, protocol, and proxy feature policy.", True),
    "ERR_URN_RESOLVE": ErrorPageInfo("ERR_URN_RESOLVE", "URN resolution failed", "DNS", "User + admin", "The proxy could not resolve the requested URN.", "Review URN resolver configuration or use a direct URL."),
    "ERR_WRITE_ERROR": ErrorPageInfo("ERR_WRITE_ERROR", "Write error", "Connectivity", "User + admin", "The proxy encountered an error writing to a connection.", "Check client/origin disconnects, network path, and socket health.", True),
    "ERR_ZERO_SIZE_OBJECT": ErrorPageInfo("ERR_ZERO_SIZE_OBJECT", "Empty response", "Origin response", "User + admin", "The origin returned no usable response body for this request.", "Check origin health and whether the empty response is expected.", True),
    "ERR_WEBFILTER_BLOCKED": ErrorPageInfo("ERR_WEBFILTER_BLOCKED", "This page is blocked", "Docker Proxy policy", "User + admin", "Docker Proxy web filtering blocked this destination.", "Review selected web-filter categories, whitelist entries, and the matching category log.", True, True),
}


def list_error_pages(*, include_custom: bool = True) -> list[ErrorPageInfo]:
    names: Iterable[str] = SQUID_ERROR_TEMPLATE_NAMES + (CUSTOM_ERROR_TEMPLATE_NAMES if include_custom else ())
    return [_INFO[name] for name in names]


def get_error_page(name: str) -> ErrorPageInfo | None:
    return _INFO.get(str(name or "").strip().upper())


def error_page_directory() -> Path:
    runtime = Path("/squid/error_pages/en")
    if runtime.exists():
        return runtime
    return Path(__file__).resolve().parents[2] / "squid" / "error_pages" / "en"


@lru_cache(maxsize=128)
def read_template(name: str) -> str:
    info = get_error_page(name)
    if info is None:
        raise KeyError(name)
    return (error_page_directory() / info.name).read_text(encoding="utf-8")


def template_tokens(text: str) -> list[str]:
    return sorted(set(_TOKEN_RE.findall(text or "")))


def missing_template_names() -> list[str]:
    base = error_page_directory()
    return [name for name in SQUID_ERROR_TEMPLATE_NAMES if not (base / name).is_file()]


def render_preview(name: str) -> str:
    info = get_error_page(name)
    if info is None:
        raise KeyError(name)
    values = dict(_SAMPLE_VALUES)
    values["%c"] = info.name
    values["%x"] = info.family.lower().replace(" ", "-")

    def replace(match: re.Match[str]) -> str:
        token = match.group(0)
        return escape(values.get(token, token))

    return _TOKEN_RE.sub(replace, read_template(info.name))
