from __future__ import annotations

import ipaddress
import threading
from dataclasses import dataclass
from typing import List, Optional, Tuple

from services.db import connect
from services.materialized_files import write_managed_text_files
from services.proxy_context import get_proxy_id
from services.runtime_helpers import now_ts as _now


@dataclass(frozen=True)
class SslFilterSettings:
    nobump_cidrs: List[Tuple[str, int]]


@dataclass(frozen=True)
class SslFilterMaterializedState:
    include_text: str
    list_text: str


class SslFilterStore:
    def __init__(
        self,
        squid_include_path: str = "/etc/squid/conf.d/10-sslfilter.conf",
        nobump_list_path: str = "/var/lib/squid-flask-proxy/sslfilter_nobump.txt",
    ):
        self.squid_include_path = squid_include_path
        self.nobump_list_path = nobump_list_path

    def _connect(self):
        return connect()

    def init_db(self) -> None:
        with self._connect() as conn:
            conn.execute(
                "CREATE TABLE IF NOT EXISTS nobump_cidrs("
                "proxy_id VARCHAR(64) NOT NULL DEFAULT 'default', "
                "cidr VARCHAR(64) NOT NULL, "
                "added_ts BIGINT NOT NULL, "
                "PRIMARY KEY(proxy_id, cidr), "
                "KEY idx_nobump_cidrs_proxy_ts (proxy_id, added_ts)"
                ")"
            )

    def list_nobump(self, limit: int = 5000) -> List[Tuple[str, int]]:
        self.init_db()
        proxy_id = get_proxy_id()
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT cidr, added_ts FROM nobump_cidrs WHERE proxy_id=%s ORDER BY added_ts DESC, cidr ASC LIMIT %s",
                (proxy_id, int(limit)),
            ).fetchall()
            out: List[Tuple[str, int]] = []
            for r in rows:
                out.append((str(r[0]), int(r[1]) if r[1] is not None else 0))
            return out

    def add_nobump(self, entry: str) -> Tuple[bool, str, str]:
        """Add a CIDR (or single IP). Returns (ok, err, canonical)."""

        self.init_db()
        raw = (entry or "").strip()
        if not raw:
            return False, "Enter a CIDR like 192.168.1.0/24 (or a single IP)", ""

        try:
            if "/" in raw:
                net = ipaddress.ip_network(raw, strict=False)
            else:
                ip = ipaddress.ip_address(raw)
                net = ipaddress.ip_network(f"{ip}/{32 if ip.version == 4 else 128}", strict=False)
        except Exception:
            return False, "Invalid CIDR/IP. Example: 10.0.0.0/8", ""

        canonical = net.with_prefixlen
        proxy_id = get_proxy_id()
        with self._connect() as conn:
            conn.execute(
                "INSERT IGNORE INTO nobump_cidrs(proxy_id, cidr, added_ts) VALUES(%s,%s,%s)",
                (proxy_id, canonical, int(_now())),
            )
        return True, "", canonical

    def remove_nobump(self, cidr: str) -> None:
        self.init_db()
        t = (cidr or "").strip()
        if not t:
            return
        proxy_id = get_proxy_id()
        with self._connect() as conn:
            conn.execute("DELETE FROM nobump_cidrs WHERE proxy_id=%s AND cidr=%s", (proxy_id, t))

    def render_materialized_state(self) -> SslFilterMaterializedState:
        self.init_db()
        rows = self.list_nobump(limit=10000)
        cidrs = [c for c, _ts in rows if c]
        list_text = ("\n".join(cidrs) + "\n") if cidrs else ""

        if cidrs:
            include_text = "\n".join(
                [
                    "# Autogenerated: SSL filtering (no-bump CIDRs)",
                    f"acl sslfilter_nobump src \"{self.nobump_list_path}\"",
                    "note ssl_exception sslfilter_nobump sslfilter_nobump",
                    "# Splice (tunnel) TLS for unmanaged/untrusted clients.",
                    "ssl_bump splice sslfilter_nobump",
                ]
            ) + "\n"
        else:
            include_text = "# Autogenerated: SSL filtering (no-bump CIDRs) - none configured\n"

        return SslFilterMaterializedState(include_text=include_text, list_text=list_text)

    def apply_squid_include(self) -> None:
        """(Re)generate the Squid include file for ssl_bump splice policy."""
        state = self.render_materialized_state()
        write_managed_text_files(
            (self.nobump_list_path, state.list_text),
            (self.squid_include_path, state.include_text),
        )


_store: Optional[SslFilterStore] = None
_store_lock = threading.Lock()


def get_sslfilter_store() -> SslFilterStore:
    global _store
    if _store is not None:
        return _store
    with _store_lock:
        if _store is None:
            _store = SslFilterStore()
            _store.init_db()
        return _store
