FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /workspace

COPY web/requirements.txt /tmp/requirements/requirements.txt
COPY web/requirements-dev.txt /tmp/requirements/requirements-dev.txt

RUN python -m pip install --upgrade pip \
    && python -m pip install -r /tmp/requirements/requirements-dev.txt