from __future__ import annotations

from pathlib import Path

from .admin_route_test_utils import add_web_to_path, load_admin_app, login_client

REPO_ROOT = Path(__file__).resolve().parents[2]

add_web_to_path()


def test_managed_error_page_manifest_has_complete_squid_template_coverage() -> None:
    from services.error_pages import CUSTOM_ERROR_TEMPLATE_NAMES, SQUID_ERROR_TEMPLATE_NAMES, list_error_pages, missing_template_names, read_template

    assert len(SQUID_ERROR_TEMPLATE_NAMES) == 42
    assert "ERR_ACCESS_DENIED" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_SECURE_CONNECT_FAIL" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_ICAP_FAILURE" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_WEBFILTER_BLOCKED" in CUSTOM_ERROR_TEMPLATE_NAMES
    assert missing_template_names() == []

    listed = {page.name for page in list_error_pages()}
    assert set(SQUID_ERROR_TEMPLATE_NAMES).issubset(listed)
    assert set(CUSTOM_ERROR_TEMPLATE_NAMES).issubset(listed)

    for name in SQUID_ERROR_TEMPLATE_NAMES + CUSTOM_ERROR_TEMPLATE_NAMES:
        text = read_template(name)
        assert "Docker Proxy" in text
        assert "%U" in text
        assert "%T" in text
        assert "%u" not in text
        assert "%R" not in text
        assert "Generated by %s" in text
        assert '<div class="user">' in text
        assert "<strong>User guidance</strong>" in text
        assert text.index("<strong>User guidance</strong>") < text.index('aria-label="Request details"')
        assert text.index("<strong>User guidance</strong>") < text.index("<strong>Administrator guidance</strong>")
        assert "100%" not in text


def test_squid_config_uses_branded_error_directory_and_proxy_image_installs_all_templates() -> None:
    squid_conf = (REPO_ROOT / "squid" / "squid.conf.template").read_text(encoding="utf-8")
    dockerfile = (REPO_ROOT / "docker" / "Dockerfile.proxy").read_text(encoding="utf-8")

    assert "error_directory /usr/share/squid/errors/en" in squid_conf
    assert "cp -f /squid/error_pages/en/ERR_* /usr/share/squid/errors/en/" in dockerfile
    assert "ERR_WEBFILTER_BLOCKED" not in dockerfile


def test_admin_error_pages_route_lists_and_previews_templates(monkeypatch, tmp_path) -> None:
    loaded = load_admin_app(monkeypatch, tmp_path)
    client = loaded.module.app.test_client()
    login_client(client)

    page = client.get("/error-pages")
    assert page.status_code == 200
    body = page.get_data(as_text=True)
    assert "Policy · Error Pages" in body
    assert "ERR_ACCESS_DENIED" in body
    assert "ERR_WEBFILTER_BLOCKED" in body
    assert "Open in new tab" in body

    preview = client.get("/error-pages/preview/ERR_DNS_FAIL")
    assert preview.status_code == 200
    assert preview.mimetype == "text/html"
    preview_body = preview.get_data(as_text=True)
    assert "DNS lookup failed" in preview_body
    assert "User guidance" in preview_body
    assert "Check the address or ask support to check DNS" in preview_body
    assert "proxy-admin@example.invalid" in preview_body
    assert "https://example.invalid/report.pdf" in preview_body
    assert "%U" not in preview_body

    assert client.get("/error-pages/preview/ERR_NOT_REAL").status_code == 404


def test_read_template_is_cached_within_process(monkeypatch) -> None:
    from services import error_pages

    error_pages.read_template.cache_clear()

    calls: list[str] = []
    original = Path.read_text

    def fake_read_text(self, *args, **kwargs):
        calls.append(self.name)
        return original(self, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", fake_read_text)

    first = error_pages.read_template("ERR_DNS_FAIL")
    second = error_pages.read_template("ERR_DNS_FAIL")

    assert first == second
    assert calls.count("ERR_DNS_FAIL") == 1
