from __future__ import annotations

import importlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import NoReturn

REPO_ROOT = Path(__file__).resolve().parents[2]


def _add_repo_paths() -> None:
    web_root = REPO_ROOT / "web"
    for path in (REPO_ROOT, web_root):
        path_str = str(path)
        if path_str not in sys.path:
            sys.path.insert(0, path_str)


def _import_sslfilter_store_module():
    _add_repo_paths()
    import services.sslfilter_store as module  # type: ignore

    importlib.reload(module)
    return module


def _import_webfilter_core_module():
    _add_repo_paths()
    import services.webfilter_core as module  # type: ignore

    importlib.reload(module)
    return module


def _import_tool_module(module_name: str):
    _add_repo_paths()
    module = importlib.import_module(f"tools.{module_name}")
    return importlib.reload(module)


def test_apply_helpers_import_shared_common_when_executed_from_app_tools(
    tmp_path,
) -> None:
    tools_dir = tmp_path / "app" / "tools"
    tools_dir.mkdir(parents=True)
    for name in ("apply_common.py", "sslfilter_apply.py", "webfilter_apply.py"):
        shutil.copy2(REPO_ROOT / "web" / "tools" / name, tools_dir / name)

    cases = (
        (
            "sslfilter_apply.py",
            "10-sslfilter.conf",
            "# Autogenerated: sslfilter apply failed\n",
        ),
        (
            "webfilter_apply.py",
            "30-webfilter.conf",
            "# Autogenerated: web filtering disabled (import failed)\n",
        ),
    )
    for script_name, output_name, safe_include in cases:
        out = tmp_path / output_name
        result = subprocess.run(
            [sys.executable, str(tools_dir / script_name), "--out", str(out)],
            cwd=tmp_path,
            check=False,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 2
        assert out.read_text(encoding="utf-8") == safe_include


def test_sslfilter_apply_squid_include_writes_materialized_files(
    tmp_path, monkeypatch
) -> None:
    module = _import_sslfilter_store_module()
    store = module.SslFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "10-sslfilter.conf"
        ),
        nobump_list_path=str(tmp_path / "var" / "lib" / "sslfilter_nobump.txt"),
        nocache_src_list_path=str(
            tmp_path / "var" / "lib" / "sslfilter_nocache_src.txt"
        ),
    )
    state = module.SslFilterMaterializedState(
        include_text="# include\nssl_bump splice sslfilter_nobump\n",
        nobump_src_list_text="10.0.0.0/8\n",
        nocache_src_list_text="192.0.2.0/24\n",
    )
    monkeypatch.setattr(store, "render_materialized_state", lambda: state)

    store.apply_squid_include()

    assert (
        Path(store.squid_include_path).read_text(encoding="utf-8") == state.include_text
    )
    assert (
        Path(store.nobump_list_path).read_text(encoding="utf-8")
        == state.nobump_src_list_text
    )
    assert (
        Path(store.nocache_src_list_path).read_text(encoding="utf-8")
        == state.nocache_src_list_text
    )


def test_webfilter_apply_squid_include_writes_materialized_files(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    state = module.WebFilterMaterializedState(
        include_text=(
            "# include\n"
            "external_acl_type webcat_deadbeef children=4 ttl=0 negative_ttl=0 %SRC %DST %URI "
            "/usr/bin/python3 /app/tools/webcat_acl.py --fail open\n"
            "acl webfilter_block_adult external webcat_deadbeef adult\n"
            "http_access deny webfilter_block_adult\n"
        ),
        whitelist_text="example.com\n",
    )
    snapshot_publish_calls = []
    monkeypatch.setattr(store, "render_materialized_state", lambda: state)
    monkeypatch.setattr(
        store,
        "_publish_webcat_snapshot_for_helper",
        lambda: snapshot_publish_calls.append(True),
    )

    def fail_if_settings_loaded() -> NoReturn:
        msg = "apply_squid_include must not require settings/MySQL before writing materialized files"
        raise AssertionError(msg)

    monkeypatch.setattr(store, "get_settings", fail_if_settings_loaded)

    store.apply_squid_include()

    assert snapshot_publish_calls == [True]
    assert (
        Path(store.squid_include_path).read_text(encoding="utf-8") == state.include_text
    )
    assert (
        Path(store.whitelist_path).read_text(encoding="utf-8") == state.whitelist_text
    )


def test_webfilter_apply_squid_include_skips_snapshot_publish_when_helper_not_rendered(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    state = module.WebFilterMaterializedState(
        include_text="# Autogenerated: web filtering disabled or no categories selected\n",
        whitelist_text="example.com\n",
    )
    snapshot_publish_calls = []
    monkeypatch.setattr(store, "render_materialized_state", lambda: state)
    monkeypatch.setattr(
        store,
        "_publish_webcat_snapshot_for_helper",
        lambda: snapshot_publish_calls.append(True),
    )

    def fail_if_settings_loaded() -> NoReturn:
        msg = "apply_squid_include must not require settings/MySQL before writing materialized files"
        raise AssertionError(msg)

    monkeypatch.setattr(store, "get_settings", fail_if_settings_loaded)

    store.apply_squid_include()

    assert snapshot_publish_calls == []
    assert store.last_webcat_snapshot_status == (
        True,
        "Web category snapshot not needed for current policy.",
    )
    assert (
        Path(store.squid_include_path).read_text(encoding="utf-8") == state.include_text
    )
    assert (
        Path(store.whitelist_path).read_text(encoding="utf-8") == state.whitelist_text
    )


def test_sslfilter_apply_logs_safe_failure_when_materialization_fails(
    tmp_path, monkeypatch, capsys
) -> None:
    module = _import_tool_module("sslfilter_apply")
    out = tmp_path / "etc" / "squid" / "conf.d" / "10-sslfilter.conf"

    class BrokenStore:
        def __init__(self, *, squid_include_path: str) -> None:
            self.squid_include_path = squid_include_path

        def apply_squid_include(self) -> None:
            msg = "database socket unavailable"
            raise RuntimeError(msg)

    monkeypatch.setitem(
        sys.modules,
        "services.sslfilter_store",
        SimpleNamespace(SslFilterStore=BrokenStore),
    )

    assert module.main(["--out", str(out)]) == 3
    assert (
        out.read_text(encoding="utf-8") == "# Autogenerated: sslfilter apply failed\n"
    )
    payload = json.loads(capsys.readouterr().err)
    assert payload["helper"] == "sslfilter_apply"
    assert payload["event"] == "apply_failed"
    assert payload["error_type"] == "RuntimeError"
    assert payload["reason"] == "Operation failed. Check server logs for details."
    assert "database socket unavailable" not in payload["reason"]


def test_sslfilter_apply_writes_safe_include_when_store_import_fails(
    tmp_path, monkeypatch, capsys
) -> None:
    module = _import_tool_module("sslfilter_apply")
    out = tmp_path / "etc" / "squid" / "conf.d" / "10-sslfilter.conf"

    monkeypatch.setitem(sys.modules, "services.sslfilter_store", SimpleNamespace())

    assert module.main(["--out", str(out)]) == 2
    assert (
        out.read_text(encoding="utf-8") == "# Autogenerated: sslfilter apply failed\n"
    )
    payload = json.loads(capsys.readouterr().err)
    assert payload["helper"] == "sslfilter_apply"
    assert payload["event"] == "import_failed"
    assert payload["reason"] == "Operation failed. Check server logs for details."


def test_webfilter_apply_logs_safe_failure_and_writes_safe_include(
    tmp_path, monkeypatch, capsys
) -> None:
    module = _import_tool_module("webfilter_apply")
    out = tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"

    class BrokenStore:
        def __init__(self, *, squid_include_path: str) -> None:
            self.squid_include_path = squid_include_path

        def apply_squid_include(self) -> None:
            msg = "database socket unavailable"
            raise RuntimeError(msg)

    monkeypatch.setitem(
        sys.modules,
        "services.webfilter_core",
        SimpleNamespace(ProxyWebFilterStore=BrokenStore),
    )

    assert module.main(["--out", str(out)]) == 3
    assert (
        out.read_text(encoding="utf-8")
        == "# Autogenerated: web filtering disabled (apply failed)\n"
    )
    payload = json.loads(capsys.readouterr().err)
    assert payload["helper"] == "webfilter_apply"
    assert payload["event"] == "apply_failed"
    assert payload["error_type"] == "RuntimeError"
    assert payload["reason"] == "Operation failed. Check server logs for details."
    assert "database socket unavailable" not in payload["reason"]


def test_webfilter_defaults_do_not_preselect_block_categories(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )

    class _Result:
        def __init__(self, row=None) -> None:
            self._row = row

        def fetchone(self):
            return self._row

        def fetchall(self):
            return []

    class _Conn:
        def __init__(self) -> None:
            self.settings: dict[tuple[str, str], str] = {}

        def execute(self, sql: str, params=()):
            if "INSERT IGNORE INTO webfilter_settings" in sql and len(params) == 3:
                proxy_id, key, value = params
                self.settings.setdefault((str(proxy_id), str(key)), str(value))
                return _Result()
            if "SELECT v FROM webfilter_settings" in sql and len(params) >= 2:
                proxy_id, key = params[:2]
                value = self.settings.get((str(proxy_id), str(key)))
                return _Result((value,) if value is not None else None)
            if "INSERT INTO webfilter_settings" in sql and len(params) == 3:
                proxy_id, key, value = params
                self.settings[str(proxy_id), str(key)] = str(value)
                return _Result()
            return _Result()

        def __enter__(self):
            return self

        def __exit__(self, *_exc):
            return False

    conn = _Conn()
    monkeypatch.setattr(store, "_connect", lambda: conn)

    store.init_db()

    assert conn.settings["default", "blocked_categories"] == ""


def test_webfilter_init_clears_disabled_legacy_default_block_categories(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )

    class _Result:
        def __init__(self, row=None) -> None:
            self._row = row

        def fetchone(self):
            return self._row

        def fetchall(self):
            return []

    class _Conn:
        def __init__(self) -> None:
            self.settings: dict[tuple[str, str], str] = {
                ("default", "enabled"): "0",
                (
                    "default",
                    "blocked_categories",
                ): module._LEGACY_DEFAULT_BLOCKED_CATEGORIES_CSV,
            }

        def execute(self, sql: str, params=()):
            if "INSERT IGNORE INTO webfilter_settings" in sql and len(params) == 3:
                proxy_id, key, value = params
                self.settings.setdefault((str(proxy_id), str(key)), str(value))
                return _Result()
            if "SELECT v FROM webfilter_settings" in sql and len(params) >= 2:
                proxy_id, key = params[:2]
                value = self.settings.get((str(proxy_id), str(key)))
                return _Result((value,) if value is not None else None)
            if "INSERT INTO webfilter_settings" in sql and len(params) == 3:
                proxy_id, key, value = params
                self.settings[str(proxy_id), str(key)] = str(value)
                return _Result()
            return _Result()

        def __enter__(self):
            return self

        def __exit__(self, *_exc):
            return False

    conn = _Conn()
    monkeypatch.setattr(store, "_connect", lambda: conn)

    store.init_db()

    assert conn.settings["default", "blocked_categories"] == ""


def test_webfilter_materialized_helper_name_tracks_safe_browsing_key(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    monkeypatch.setattr(
        store, "_resolve_category_aliases", lambda categories: categories
    )
    monkeypatch.setattr(store, "_webcat_built_ts", lambda: 0)

    def render_for_key(api_key: str) -> str:
        settings = module.WebFilterSettings(
            enabled=True,
            source_url="",
            blocked_categories=["adult"],
            whitelist_domains=[],
            last_success=0,
            last_attempt=0,
            last_error="",
            next_run_ts=0,
            safe_browsing_enabled=True,
            safe_browsing_api_key=api_key,
            safe_browsing_lists=["mw-4b"],
        )
        monkeypatch.setattr(store, "get_settings", lambda: settings)
        return store.render_materialized_state().include_text

    first = render_for_key("first-secret")
    second = render_for_key("second-secret")

    assert first != second
    assert "first-secret" not in first
    assert "second-secret" not in second
    assert "/app/tools/safe_browsing_acl.py" in first
    assert "/app/tools/safe_browsing_acl.py" in second


def test_webfilter_materialized_categories_are_canonicalized_before_acl_render(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    settings = module.WebFilterSettings(
        enabled=True,
        source_url="",
        blocked_categories=[
            "Adult Sites",
            "residential proxies",
            "MALWARE<script>",
            "Adult Sites",
        ],
        whitelist_domains=[],
        last_success=0,
        last_attempt=0,
        last_error="",
        next_run_ts=0,
    )

    class _Rows:
        def fetchall(self):
            return [
                ("adult_sites", "adult"),
                ("residential_proxies", "proxies"),
            ]

    class _Conn:
        def execute(self, sql: str, params=()):
            assert "FROM webcat_aliases" in sql
            assert params == (
                "adult_sites",
                "residential_proxies",
                "malwarescript",
                "adult_sites",
            )
            return _Rows()

        def __enter__(self):
            return self

        def __exit__(self, *_exc):
            return False

    monkeypatch.setattr(store, "get_settings", lambda: settings)
    monkeypatch.setattr(
        module, "table_exists", lambda _conn, name: name == "webcat_aliases"
    )

    def connect_webcat() -> _Conn:
        return _Conn()

    monkeypatch.setattr(store, "_connect_webcat", connect_webcat)
    monkeypatch.setattr(store, "_webcat_built_ts", lambda: 0)

    rendered = store.render_materialized_state().include_text

    assert "acl webfilter_block_adult external" in rendered
    assert "acl webfilter_block_proxies external" in rendered
    assert "acl webfilter_block_malwarescript external" in rendered
    assert "Adult Sites" not in rendered
    assert "residential proxies" not in rendered
    assert "MALWARE<script>" not in rendered


def test_webfilter_materialized_helpers_honor_fail_mode_env(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    settings = module.WebFilterSettings(
        enabled=True,
        source_url="",
        blocked_categories=["adult"],
        whitelist_domains=[],
        last_success=0,
        last_attempt=0,
        last_error="",
        next_run_ts=0,
        safe_browsing_enabled=True,
        safe_browsing_api_key="test-key",
    )
    monkeypatch.setenv("WEBFILTER_FAIL", "closed")
    monkeypatch.setenv("SAFE_BROWSING_FAIL", "closed")
    monkeypatch.setattr(store, "get_settings", lambda: settings)
    monkeypatch.setattr(
        store, "_resolve_category_aliases", lambda categories: categories
    )
    monkeypatch.setattr(store, "_webcat_built_ts", lambda: 0)

    rendered = store.render_materialized_state().include_text

    assert "/app/tools/webcat_acl.py --fail closed" in rendered
    assert "/app/tools/safe_browsing_acl.py --fail closed" in rendered


def test_webfilter_materialized_safe_browsing_helper_receives_selected_lists(
    tmp_path, monkeypatch
) -> None:
    module = _import_webfilter_core_module()
    store = module.ProxyWebFilterStore(
        squid_include_path=str(
            tmp_path / "etc" / "squid" / "conf.d" / "30-webfilter.conf"
        ),
        whitelist_path=str(tmp_path / "var" / "lib" / "webfilter_whitelist.txt"),
    )
    settings = module.WebFilterSettings(
        enabled=True,
        source_url="",
        blocked_categories=[],
        whitelist_domains=[],
        last_success=0,
        last_attempt=0,
        last_error="",
        next_run_ts=0,
        safe_browsing_enabled=True,
        safe_browsing_api_key="test-key",
        safe_browsing_lists=["se-4b", "invalid-list", "uwsa-4b"],
    )
    monkeypatch.setattr(store, "get_settings", lambda: settings)
    monkeypatch.setattr(
        store, "_resolve_category_aliases", lambda categories: categories
    )
    monkeypatch.setattr(store, "_webcat_built_ts", lambda: 0)

    rendered = store.render_materialized_state().include_text

    assert "safe_browsing_acl.py --fail open --list se-4b --list uwsa-4b" in rendered
    assert "invalid-list" not in rendered


def test_write_managed_text_files_restores_previous_files_when_late_replace_fails(
    tmp_path, monkeypatch
) -> None:
    _add_repo_paths()
    from services import materialized_files  # type: ignore

    first = tmp_path / "first.conf"
    second = tmp_path / "second.conf"
    first.write_text("old first\n", encoding="utf-8")
    second.write_text("old second\n", encoding="utf-8")
    real_replace = materialized_files.os.replace
    replace_calls: list[tuple[str, str]] = []

    def flaky_replace(src, dst):
        replace_calls.append((str(src), str(dst)))
        if str(dst) == str(second):
            msg = "disk full"
            raise OSError(msg)
        return real_replace(src, dst)

    monkeypatch.setattr(materialized_files.os, "replace", flaky_replace)

    try:
        materialized_files.write_managed_text_files(
            (str(first), "new first\n"), (str(second), "new second\n")
        )
    except OSError as exc:
        assert "disk full" in str(exc)
    else:  # pragma: no cover - defensive assertion
        msg = "expected second replace failure"
        raise AssertionError(msg)

    assert any(dst == str(second) for _src, dst in replace_calls)
    assert first.read_text(encoding="utf-8") == "old first\n"
    assert second.read_text(encoding="utf-8") == "old second\n"


def test_write_managed_text_files_restores_via_staged_replace(
    tmp_path, monkeypatch
) -> None:
    _add_repo_paths()
    from services import materialized_files  # type: ignore

    first = tmp_path / "first.conf"
    second = tmp_path / "second.conf"
    first.write_text("old first\n", encoding="utf-8")
    second.write_text("old second\n", encoding="utf-8")
    real_replace = materialized_files.os.replace

    def flaky_replace(src, dst):
        if str(dst) == str(second):
            msg = "disk full"
            raise OSError(msg)
        return real_replace(src, dst)

    def reject_direct_restore(*_args, **_kwargs) -> NoReturn:
        msg = "rollback must not write directly to the live materialized file"
        raise AssertionError(msg)

    monkeypatch.setattr(materialized_files.os, "replace", flaky_replace)
    monkeypatch.setattr(Path, "write_bytes", reject_direct_restore)

    try:
        materialized_files.write_managed_text_files(
            (str(first), "new first\n"), (str(second), "new second\n")
        )
    except OSError as exc:
        assert "disk full" in str(exc)
    else:  # pragma: no cover - defensive assertion
        msg = "expected second replace failure"
        raise AssertionError(msg)

    assert first.read_text(encoding="utf-8") == "old first\n"
    assert second.read_text(encoding="utf-8") == "old second\n"


def test_write_managed_text_files_restores_previous_file_mode_on_rollback(
    tmp_path, monkeypatch
) -> None:
    _add_repo_paths()
    from services import materialized_files  # type: ignore

    first = tmp_path / "first.conf"
    second = tmp_path / "second.conf"
    first.write_text("old first\n", encoding="utf-8")
    second.write_text("old second\n", encoding="utf-8")
    first.chmod(0o600)
    second.chmod(0o640)
    real_replace = materialized_files.os.replace

    def flaky_replace(src, dst):
        if str(dst) == str(second):
            msg = "disk full"
            raise OSError(msg)
        return real_replace(src, dst)

    monkeypatch.setattr(materialized_files.os, "replace", flaky_replace)

    try:
        materialized_files.write_managed_text_files(
            (str(first), "new first\n"), (str(second), "new second\n")
        )
    except OSError as exc:
        assert "disk full" in str(exc)
    else:  # pragma: no cover - defensive assertion
        msg = "expected second replace failure"
        raise AssertionError(msg)

    assert first.read_text(encoding="utf-8") == "old first\n"
    assert second.read_text(encoding="utf-8") == "old second\n"
    assert first.stat().st_mode & 0o777 == 0o600
    assert second.stat().st_mode & 0o777 == 0o640


def test_write_managed_text_files_keeps_runtime_files_world_readable(tmp_path) -> None:
    _add_repo_paths()
    from services import materialized_files  # type: ignore

    include_path = tmp_path / "conf.d" / "30-webfilter.conf"
    list_path = tmp_path / "webfilter_whitelist.txt"

    materialized_files.write_managed_text_files(
        (str(include_path), "include text\n"),
        (str(list_path), "example.com\n"),
    )

    assert include_path.read_text(encoding="utf-8") == "include text\n"
    assert list_path.read_text(encoding="utf-8") == "example.com\n"
    assert include_path.stat().st_mode & 0o777 == 0o644
    assert list_path.stat().st_mode & 0o777 == 0o644
