from __future__ import annotations

import re
import subprocess
from html.parser import HTMLParser
from pathlib import Path

import pytest

from .admin_route_test_utils import add_web_to_path, load_admin_app, login_client

REPO_ROOT = Path(__file__).resolve().parents[2]

add_web_to_path()

from services import error_pages  # type: ignore  # noqa: E402

BLOCK_REASON_TEMPLATE_NAMES = {
    "ERR_ACCESS_DENIED",
    "ERR_ACL_TIME_QUOTA_EXCEEDED",
    "ERR_CACHE_ACCESS_DENIED",
    "ERR_CACHE_MGR_ACCESS_DENIED",
    "ERR_FORWARDING_DENIED",
    "ERR_FTP_DISABLED",
    "ERR_FTP_FORBIDDEN",
    "ERR_TOO_BIG",
    "ERR_WEBFILTER_BLOCKED",
}

EXPECTED_SQUID_TRACKED_FILES = [
    "squid/error_pages/README.md",
    "squid/error_pages/en/ERR_ACCESS_DENIED",
    "squid/error_pages/en/ERR_ACL_TIME_QUOTA_EXCEEDED",
    "squid/error_pages/en/ERR_AGENT_CONFIGURE",
    "squid/error_pages/en/ERR_AGENT_WPAD",
    "squid/error_pages/en/ERR_CACHE_ACCESS_DENIED",
    "squid/error_pages/en/ERR_CACHE_MGR_ACCESS_DENIED",
    "squid/error_pages/en/ERR_CANNOT_FORWARD",
    "squid/error_pages/en/ERR_CONFLICT_HOST",
    "squid/error_pages/en/ERR_CONNECT_FAIL",
    "squid/error_pages/en/ERR_DIR_LISTING",
    "squid/error_pages/en/ERR_DNS_FAIL",
    "squid/error_pages/en/ERR_ESI",
    "squid/error_pages/en/ERR_FORWARDING_DENIED",
    "squid/error_pages/en/ERR_FTP_DISABLED",
    "squid/error_pages/en/ERR_FTP_FAILURE",
    "squid/error_pages/en/ERR_FTP_FORBIDDEN",
    "squid/error_pages/en/ERR_FTP_NOT_FOUND",
    "squid/error_pages/en/ERR_FTP_PUT_CREATED",
    "squid/error_pages/en/ERR_FTP_PUT_ERROR",
    "squid/error_pages/en/ERR_FTP_PUT_MODIFIED",
    "squid/error_pages/en/ERR_FTP_UNAVAILABLE",
    "squid/error_pages/en/ERR_GATEWAY_FAILURE",
    "squid/error_pages/en/ERR_ICAP_FAILURE",
    "squid/error_pages/en/ERR_INVALID_REQ",
    "squid/error_pages/en/ERR_INVALID_RESP",
    "squid/error_pages/en/ERR_INVALID_URL",
    "squid/error_pages/en/ERR_LIFETIME_EXP",
    "squid/error_pages/en/ERR_NO_RELAY",
    "squid/error_pages/en/ERR_ONLY_IF_CACHED_MISS",
    "squid/error_pages/en/ERR_PRECONDITION_FAILED",
    "squid/error_pages/en/ERR_PROTOCOL_UNKNOWN",
    "squid/error_pages/en/ERR_READ_ERROR",
    "squid/error_pages/en/ERR_READ_TIMEOUT",
    "squid/error_pages/en/ERR_SECURE_CONNECT_FAIL",
    "squid/error_pages/en/ERR_SHUTTING_DOWN",
    "squid/error_pages/en/ERR_SOCKET_FAILURE",
    "squid/error_pages/en/ERR_TOO_BIG",
    "squid/error_pages/en/ERR_UNSUP_HTTPVERSION",
    "squid/error_pages/en/ERR_UNSUP_REQ",
    "squid/error_pages/en/ERR_URN_RESOLVE",
    "squid/error_pages/en/ERR_WEBFILTER_BLOCKED",
    "squid/error_pages/en/ERR_WRITE_ERROR",
    "squid/error_pages/en/ERR_ZERO_SIZE_OBJECT",
    "squid/squid.conf.template",
    "squid/ssl/README.md",
]


class _ErrorPageAttributeScanner(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.raw_token_attributes: list[tuple[str, str, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        for attr, value in attrs:
            if value and re.search(r"%(?:[A-Za-z]|%)", value):
                self.raw_token_attributes.append((tag, attr, value))


def test_tracked_squid_inventory_matches_audited_contract() -> None:
    result = subprocess.run(
        ["git", "ls-files", "squid"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert result.stdout.splitlines() == EXPECTED_SQUID_TRACKED_FILES
    assert len(EXPECTED_SQUID_TRACKED_FILES) == 46


def test_managed_error_page_manifest_has_complete_squid_template_coverage() -> None:
    from services.error_pages import (
        CUSTOM_ERROR_TEMPLATE_NAMES,
        SQUID_ERROR_TEMPLATE_NAMES,
        list_error_pages,
        missing_template_names,
        read_template,
    )

    assert len(SQUID_ERROR_TEMPLATE_NAMES) == 42
    assert "ERR_ACCESS_DENIED" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_SECURE_CONNECT_FAIL" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_ICAP_FAILURE" in SQUID_ERROR_TEMPLATE_NAMES
    assert "ERR_WEBFILTER_BLOCKED" in CUSTOM_ERROR_TEMPLATE_NAMES
    assert missing_template_names() == []

    listed = {page.name for page in list_error_pages()}
    assert set(SQUID_ERROR_TEMPLATE_NAMES).issubset(listed)
    assert set(CUSTOM_ERROR_TEMPLATE_NAMES).issubset(listed)

    for name in SQUID_ERROR_TEMPLATE_NAMES + CUSTOM_ERROR_TEMPLATE_NAMES:
        text = read_template(name)
        assert "Docker Proxy" in text
        assert "%U" in text
        assert "%T" in text
        assert "%u" not in text
        assert "%R" not in text
        assert "Generated by %s" in text
        assert '<div class="user">' in text
        assert "<strong>User guidance</strong>" in text
        assert text.index("<strong>User guidance</strong>") < text.index(
            'aria-label="Request details"'
        )
        assert text.index("<strong>User guidance</strong>") < text.index(
            "<strong>Administrator guidance</strong>"
        )
        assert "100%" not in text


def test_error_pages_do_not_embed_raw_squid_tokens_in_html_attributes() -> None:
    from services.error_pages import (
        CUSTOM_ERROR_TEMPLATE_NAMES,
        SQUID_ERROR_TEMPLATE_NAMES,
    )

    for name in SQUID_ERROR_TEMPLATE_NAMES + CUSTOM_ERROR_TEMPLATE_NAMES:
        text = (REPO_ROOT / "squid" / "error_pages" / "en" / name).read_text(
            encoding="utf-8"
        )
        scanner = _ErrorPageAttributeScanner()
        scanner.feed(text)

        assert scanner.raw_token_attributes == [], name


def test_missing_template_names_reports_custom_templates_by_default(
    monkeypatch, tmp_path
) -> None:
    from services.error_pages import (
        SQUID_ERROR_TEMPLATE_NAMES,
        error_page_directory,
        missing_template_names,
    )

    error_page_directory.cache_clear()
    monkeypatch.setattr(error_pages, "error_page_directory", lambda: tmp_path)
    for name in SQUID_ERROR_TEMPLATE_NAMES:
        (tmp_path / name).write_text("placeholder", encoding="utf-8")

    try:
        assert missing_template_names() == ["ERR_WEBFILTER_BLOCKED"]
        assert missing_template_names(include_custom=False) == []
    finally:
        error_page_directory.cache_clear()


def test_access_denied_page_explains_block_reason() -> None:
    from services.error_pages import read_template, render_preview

    text = read_template("ERR_ACCESS_DENIED")
    assert '<div class="reason">' in text
    assert "<strong>Block reason</strong>" in text
    assert text.index("<strong>User guidance</strong>") < text.index(
        "<strong>Block reason</strong>"
    )
    assert text.index("<strong>Block reason</strong>") < text.index(
        'aria-label="Request details"'
    )
    assert "%o" in text
    assert "%m" in text
    assert "category=malware" in render_preview("ERR_ACCESS_DENIED")


def test_policy_error_pages_explain_block_reason() -> None:
    from services.error_pages import read_template, render_preview

    for name in sorted(BLOCK_REASON_TEMPLATE_NAMES):
        text = read_template(name)
        assert '<div class="reason">' in text, name
        assert "<strong>Block reason</strong>" in text, name
        assert ".reason { margin:" in text, name
        assert text.index("<strong>User guidance</strong>") < text.index(
            "<strong>Block reason</strong>"
        ), name
        assert text.index("<strong>Block reason</strong>") < text.index(
            'aria-label="Request details"'
        ), name
        assert "%o" in text, name

    assert "category=malware" in render_preview("ERR_WEBFILTER_BLOCKED")


def test_squid_config_uses_branded_error_directory_and_proxy_image_installs_all_templates() -> (
    None
):
    squid_conf = (REPO_ROOT / "squid" / "squid.conf.template").read_text(
        encoding="utf-8"
    )
    dockerfile = (REPO_ROOT / "docker" / "Dockerfile.proxy").read_text(encoding="utf-8")

    assert "error_directory /usr/share/squid/errors/en" in squid_conf
    assert "cp -f /squid/error_pages/en/ERR_* /usr/share/squid/errors/en/" in dockerfile
    assert "ERR_WEBFILTER_BLOCKED" not in dockerfile


def test_admin_error_pages_route_lists_and_previews_templates(
    monkeypatch, tmp_path
) -> None:
    loaded = load_admin_app(monkeypatch, tmp_path)
    client = loaded.module.app.test_client()
    login_client(client)

    page = client.get("/error-pages")
    assert page.status_code == 200
    body = page.get_data(as_text=True)
    assert "Policy · Error Pages" in body
    assert "ERR_ACCESS_DENIED" in body
    assert "ERR_WEBFILTER_BLOCKED" in body
    assert "Open in new tab" in body

    preview = client.get("/error-pages/preview/ERR_DNS_FAIL")
    assert preview.status_code == 200
    assert preview.mimetype == "text/html"
    preview_body = preview.get_data(as_text=True)
    assert "DNS lookup failed" in preview_body
    assert "User guidance" in preview_body
    assert "Check the address or ask support to check DNS" in preview_body
    assert "proxy-admin@example.invalid" in preview_body
    assert "https://example.invalid/report.pdf" in preview_body
    assert "%U" not in preview_body

    assert client.get("/error-pages/preview/ERR_NOT_REAL").status_code == 404


def test_admin_error_pages_route_surfaces_missing_template_in_manifest(
    monkeypatch, tmp_path
) -> None:
    from services.error_pages import (
        CUSTOM_ERROR_TEMPLATE_NAMES,
        SQUID_ERROR_TEMPLATE_NAMES,
    )

    template_dir = tmp_path / "templates"
    template_dir.mkdir()
    missing_name = "ERR_DNS_FAIL"
    for name in SQUID_ERROR_TEMPLATE_NAMES + CUSTOM_ERROR_TEMPLATE_NAMES:
        if name != missing_name:
            (template_dir / name).write_text(
                "Docker Proxy %U %T Generated by %s", encoding="utf-8"
            )

    error_pages.error_page_directory.cache_clear()
    monkeypatch.setattr(error_pages, "error_page_directory", lambda: template_dir)

    loaded = load_admin_app(monkeypatch, tmp_path)
    client = loaded.module.app.test_client()
    login_client(client)

    page = client.get("/error-pages")
    assert page.status_code == 200
    body = page.get_data(as_text=True)
    assert missing_name in body
    assert "Missing/unavailable" in body
    assert "Template file is missing or unreadable" in body
    assert "ERR_ACCESS_DENIED" in body
    assert "%T, %U, %s" in body

    preview = client.get(f"/error-pages/preview/{missing_name}")
    assert preview.status_code == 404


def test_non_regular_and_symlink_templates_are_unavailable(
    monkeypatch, tmp_path
) -> None:
    template_path = tmp_path / "ERR_DNS_FAIL"
    template_path.mkdir()
    monkeypatch.setattr(error_pages, "error_page_directory", lambda: tmp_path)

    assert "ERR_DNS_FAIL" in error_pages.missing_template_names()
    with pytest.raises(OSError, match="not a regular file"):
        error_pages.read_template("ERR_DNS_FAIL")

    template_path.rmdir()
    target = tmp_path / "outside-template"
    target.write_text("outside content", encoding="utf-8")
    template_path.symlink_to(target)

    assert "ERR_DNS_FAIL" in error_pages.missing_template_names()
    with pytest.raises(OSError, match="not a regular file"):
        error_pages.render_preview("ERR_DNS_FAIL")


def test_template_file_cache_refreshes_after_replacement(monkeypatch, tmp_path) -> None:
    template_path = tmp_path / "ERR_DNS_FAIL"
    template_path.write_text("original %U", encoding="utf-8")
    monkeypatch.setattr(error_pages, "error_page_directory", lambda: tmp_path)

    calls: list[str] = []
    original = Path.read_text

    def fake_read_text(self, *args, **kwargs):
        calls.append(self.name)
        return original(self, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", fake_read_text)

    first = error_pages.read_template("ERR_DNS_FAIL")
    second = error_pages.read_template("ERR_DNS_FAIL")
    template_path.write_text("replacement content %T", encoding="utf-8")
    third = error_pages.read_template("ERR_DNS_FAIL")

    assert first == second
    assert third == "replacement content %T"
    assert calls == ["ERR_DNS_FAIL", "ERR_DNS_FAIL"]


def test_missing_template_and_preview_follow_filesystem_changes(
    monkeypatch, tmp_path
) -> None:
    template_path = tmp_path / "ERR_DNS_FAIL"
    template_path.write_text("original %U", encoding="utf-8")
    monkeypatch.setattr(error_pages, "error_page_directory", lambda: tmp_path)

    assert (
        error_pages.render_preview("ERR_DNS_FAIL")
        == "original https://example.invalid/report.pdf"
    )

    template_path.write_text("replacement %T", encoding="utf-8")
    assert (
        error_pages.render_preview("ERR_DNS_FAIL")
        == "replacement Sun, 10 May 2026 15:15:30 GMT"
    )

    template_path.unlink()
    assert "ERR_DNS_FAIL" in error_pages.missing_template_names()


def test_template_tokens_are_cached() -> None:
    error_pages.template_tokens.cache_clear()

    tokens_1 = error_pages.template_tokens("A %U B %T")
    tokens_2 = error_pages.template_tokens("A %U B %T")

    assert tokens_1 == tokens_2 == ("%T", "%U")
    assert error_pages.template_tokens.cache_info().hits == 1
