#!/usr/bin/env python3
from __future__ import annotations

import argparse
import contextlib
import pathlib
import sys


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate /etc/squid/conf.d/10-sslfilter.conf from UI settings",
    )
    ap.add_argument("--out", default="/etc/squid/conf.d/10-sslfilter.conf")
    args = ap.parse_args()

    sys.path.insert(0, "/app")
    try:
        from services.sslfilter_store import SslFilterStore  # type: ignore
    except Exception:
        return 2

    store = SslFilterStore(squid_include_path=args.out)
    try:
        store.apply_squid_include()
        return 0
    except Exception:
        pathlib.Path(pathlib.Path(args.out).parent).mkdir(exist_ok=True, parents=True)
        with contextlib.suppress(Exception):
            pathlib.Path(args.out).write_text(
                "# Autogenerated: sslfilter apply failed\n", encoding="utf-8",
            )
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
