#!/usr/bin/env python3
from __future__ import annotations

import argparse
import contextlib
import sys
from typing import TYPE_CHECKING

try:
    from tools.apply_common import emit_helper_failure, write_safe_include
except ModuleNotFoundError:  # pragma: no cover - direct script execution path
    from apply_common import emit_helper_failure, write_safe_include

if TYPE_CHECKING:
    from collections.abc import Sequence

HELPER_NAME = "sslfilter_apply"
SAFE_INCLUDE_TEXT = "# Autogenerated: sslfilter apply failed\n"


def _emit_failure(event: str, exc: Exception) -> None:
    emit_helper_failure(HELPER_NAME, event, exc)


def _write_safe_include(path: str) -> None:
    write_safe_include(path, SAFE_INCLUDE_TEXT)


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate /etc/squid/conf.d/10-sslfilter.conf from UI settings",
    )
    ap.add_argument("--out", default="/etc/squid/conf.d/10-sslfilter.conf")
    args = ap.parse_args(list(argv) if argv is not None else None)

    sys.path.insert(0, "/app")
    try:
        from services.sslfilter_store import SslFilterStore  # type: ignore
    except Exception as exc:
        _emit_failure("import_failed", exc)
        with contextlib.suppress(Exception):
            _write_safe_include(args.out)
        return 2

    store = SslFilterStore(squid_include_path=args.out)
    try:
        store.apply_squid_include()
        return 0
    except Exception as exc:
        _emit_failure("apply_failed", exc)
        with contextlib.suppress(Exception):
            _write_safe_include(args.out)
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
