#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys


def _write_safe_include(path: str, reason: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Autogenerated: web filtering disabled ({reason})\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate /etc/squid/conf.d/30-webfilter.conf from UI settings")
    ap.add_argument("--out", default="/etc/squid/conf.d/30-webfilter.conf")
    args = ap.parse_args()

    # Import from the app package (works in container where /app is present).
    sys.path.insert(0, "/app")
    try:
        from services.webfilter_core import ProxyWebFilterStore
    except Exception as e:
        print(f"[webfilter] import failed: {type(e).__name__}: {e}", file=sys.stderr)
        try:
            _write_safe_include(args.out, "import failed")
        except Exception:
            pass
        return 2

    store = ProxyWebFilterStore(squid_include_path=args.out)
    try:
        store.apply_squid_include()
        snapshot_ok, snapshot_detail = getattr(store, "last_webcat_snapshot_status", (True, ""))
        if not snapshot_ok:
            print(f"[webfilter] warning: {snapshot_detail}", file=sys.stderr)
        return 0
    except Exception as e:
        print(f"[webfilter] apply failed: {type(e).__name__}: {e}", file=sys.stderr)
        # Ensure include exists so Squid include is safe.
        try:
            _write_safe_include(args.out, "apply failed")
        except Exception:
            pass
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
