from __future__ import annotations

import ipaddress
import os
import sqlite3
import time
from dataclasses import dataclass
from typing import List, Optional, Tuple


def _now() -> int:
    return int(time.time())


@dataclass(frozen=True)
class SslFilterSettings:
    nobump_cidrs: List[Tuple[str, int]]


class SslFilterStore:
    def __init__(
        self,
        db_path: str = "/var/lib/squid-flask-proxy/sslfilter.db",
        squid_include_path: str = "/etc/squid/conf.d/10-sslfilter.conf",
        nobump_list_path: str = "/var/lib/squid-flask-proxy/sslfilter_nobump.txt",
    ):
        self.db_path = db_path
        self.squid_include_path = squid_include_path
        self.nobump_list_path = nobump_list_path

    def _connect(self) -> sqlite3.Connection:
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        conn = sqlite3.connect(self.db_path, timeout=3, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.execute("PRAGMA synchronous=NORMAL;")
        return conn

    def init_db(self) -> None:
        with self._connect() as conn:
            conn.execute(
                "CREATE TABLE IF NOT EXISTS nobump_cidrs("
                "cidr TEXT PRIMARY KEY, "
                "added_ts INTEGER NOT NULL"
                ");"
            )

    def list_nobump(self, limit: int = 5000) -> List[Tuple[str, int]]:
        self.init_db()
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT cidr, added_ts FROM nobump_cidrs ORDER BY added_ts DESC, cidr ASC LIMIT ?",
                (int(limit),),
            ).fetchall()
            out: List[Tuple[str, int]] = []
            for r in rows:
                out.append((str(r[0]), int(r[1]) if r[1] is not None else 0))
            return out

    def add_nobump(self, entry: str) -> Tuple[bool, str, str]:
        """Add a CIDR (or single IP). Returns (ok, err, canonical)."""

        self.init_db()
        raw = (entry or "").strip()
        if not raw:
            return False, "Enter a CIDR like 192.168.1.0/24 (or a single IP)", ""

        try:
            if "/" in raw:
                net = ipaddress.ip_network(raw, strict=False)
            else:
                ip = ipaddress.ip_address(raw)
                net = ipaddress.ip_network(f"{ip}/{32 if ip.version == 4 else 128}", strict=False)
        except Exception:
            return False, "Invalid CIDR/IP. Example: 10.0.0.0/8", ""

        canonical = net.with_prefixlen
        with self._connect() as conn:
            conn.execute(
                "INSERT OR IGNORE INTO nobump_cidrs(cidr, added_ts) VALUES(?,?)",
                (canonical, int(_now())),
            )
        return True, "", canonical

    def remove_nobump(self, cidr: str) -> None:
        self.init_db()
        t = (cidr or "").strip()
        if not t:
            return
        with self._connect() as conn:
            conn.execute("DELETE FROM nobump_cidrs WHERE cidr=?", (t,))

    def apply_squid_include(self) -> None:
        """(Re)generate the Squid include file for ssl_bump splice policy."""

        self.init_db()
        rows = self.list_nobump(limit=10000)
        cidrs = [c for c, _ts in rows if c]

        os.makedirs(os.path.dirname(self.squid_include_path), exist_ok=True)
        os.makedirs(os.path.dirname(self.nobump_list_path), exist_ok=True)

        if cidrs:
            # Squid can read IP/CIDR lists from a file for src ACLs.
            with open(self.nobump_list_path, "w", encoding="utf-8") as f:
                for c in cidrs:
                    f.write(c + "\n")

            lines = [
                "# Autogenerated: SSL filtering (no-bump CIDRs)",
                f"acl sslfilter_nobump src \"{self.nobump_list_path}\"",
                "# Splice (tunnel) TLS for unmanaged/untrusted clients.",
                "ssl_bump splice sslfilter_nobump",
            ]
        else:
            # No entries: do not add a splice rule. Squid's existing bump rules apply.
            # Note: squid.conf.template still contains 'ssl_bump bump all'.
            lines = ["# Autogenerated: SSL filtering (no-bump CIDRs) - none configured"]

        with open(self.squid_include_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")


_store: Optional[SslFilterStore] = None


def get_sslfilter_store() -> SslFilterStore:
    global _store
    if _store is None:
        _store = SslFilterStore()
        _store.init_db()
    return _store
