#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate /etc/squid/conf.d/10-sslfilter.conf from UI settings")
    ap.add_argument("--db", default="/var/lib/squid-flask-proxy/sslfilter.db")
    ap.add_argument("--out", default="/etc/squid/conf.d/10-sslfilter.conf")
    args = ap.parse_args()

    sys.path.insert(0, "/app")
    try:
        from services.sslfilter_store import SslFilterStore  # type: ignore
    except Exception as e:
        print(f"[sslfilter] import failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 2

    store = SslFilterStore(db_path=args.db, squid_include_path=args.out)
    try:
        store.apply_squid_include()
        return 0
    except Exception as e:
        print(f"[sslfilter] apply failed: {type(e).__name__}: {e}", file=sys.stderr)
        os.makedirs(os.path.dirname(args.out), exist_ok=True)
        try:
            with open(args.out, "w", encoding="utf-8") as f:
                f.write("# Autogenerated: sslfilter apply failed\n")
        except Exception:
            pass
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
